# Generated by Django 6.0.5 on 2026-05-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kingdom", "0001_initial"),
        ("world", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="kingdom",
            constraint=models.UniqueConstraint(
                fields=("world", "name"), name="unique_kingdom_name_per_world"
            ),
        ),
    ]
