# Generated by Django 6.0.5 on 2026-05-20 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="World",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
                (
                    "terrain",
                    models.CharField(
                        choices=[
                            ("grass", "Grass"),
                            ("mountain", "Mountain"),
                            ("desert", "Desert"),
                        ],
                        default="grass",
                        max_length=20,
                    ),
                ),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="world.world"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["world", "x", "y"], name="world_tile_world_i_703db7_idx"
                    )
                ],
                "unique_together": {("world", "x", "y")},
            },
        ),
    ]
