# Generated by Django 6.0.5 on 2026-05-20 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kingdom", "0002_kingdom_unique_kingdom_name_per_world"),
        ("world", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tile",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tiles",
                to="kingdom.kingdom",
            ),
        ),
    ]
